version: '2'

services:
  nginx:
    image: hub.c.163.com/library/nginx:1.12.0
    container_name: demo-nginx
    env_file: .env
    links:
      - phpfpm
    ports:
      - 80:80
    volumes:
      - ./etc/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www/html

  phpfpm:
    image: localphp
    container_name: demo-php
    env_file: .env
    ports:
      - 9000:9000
    links:
      - mysql
      - redis
    volumes:
      - .:/var/www/html

  mysql:
    image: hub.c.163.com/library/mysql:5.6.29
    container_name: demo-mysql
    env_file: .env
    ports:
      - 3306:3306
    volumes:
      - ~/data/demo/mysql:/var/lib/mysql

  redis:
    image: hub.c.163.com/library/redis:3.2.6
    container_name: demo-redis
    env_file: .env
    ports:
      - 6379:6379
    volumes:
      - ~/data/demo/redis:/data
